version: '3.8'

services:
  app:
    build: 
      context: ./payment-service-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - PAYMENT_METHOD_API_URL=http://payment-method-api:8000
    volumes:
      - ./payment-service-api/logs:/app/logs
    depends_on:
      - db
      - payment-method-api

  payment-method-api:
    build: ./payment-method-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:password@payment-method-db:5432/postgres
    depends_on:
      - payment-method-db

  payment-method-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - payment_method_db_data:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  payment_method_db_data: 